//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voxpopuliAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campania
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campania()
        {
            this.ControlVotacion = new HashSet<ControlVotacion>();
            this.RespuestaCampania = new HashSet<RespuestaCampania>();
            this.CampaniaDetalle = new HashSet<CampaniaDetalle>();
        }
    
        public int CampaniaId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public byte Estatus { get; set; }
        public int TipoCampaniaId { get; set; }
        public System.DateTime FechaInicia { get; set; }
        public System.DateTime FechaFinaliza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlVotacion> ControlVotacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RespuestaCampania> RespuestaCampania { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaniaDetalle> CampaniaDetalle { get; set; }
    }
}
