//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voxpopuliAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlVotacion
    {
        public int CampaniaId { get; set; }
        public string DeviceId { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Campania Campania { get; set; }
    }
}
