//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voxpopuliAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class voxpopuliDBEntities : DbContext
    {
        public voxpopuliDBEntities()
            : base("name=voxpopuliDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Campania> Campania { get; set; }
        public virtual DbSet<CampaniaDetalle> CampaniaDetalle { get; set; }
        public virtual DbSet<ControlPregunta> ControlPregunta { get; set; }
        public virtual DbSet<ControlVotacion> ControlVotacion { get; set; }
        public virtual DbSet<Pregunta> Pregunta { get; set; }
        public virtual DbSet<Respuesta> Respuesta { get; set; }
        public virtual DbSet<RespuestaCampania> RespuestaCampania { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoControl> TipoControl { get; set; }
    }
}
